# .github/workflows/day0-ci.yml
name: day0-ci
on:
  push:
    paths:
      - 'MLOps/Wildfire/**'
      - '.github/workflows/day0-ci.yml'
  workflow_dispatch: 
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: MLOps/Wildfire
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pystac-client planetary-computer rasterio pytest

      - name: Run smoke test
        run: pytest tests/ -v
